build.gradle, src/main/java/com/beside/archivist/config/SecurityConfig.java, src/main/java/com/beside/archivist/config/WebClientConfig.java, src/main/java/com/beside/archivist/controller/KakaoLoginController.java, src/main/java/com/beside/archivist/dto/KakaoLoginDto.java, src/main/java/com/beside/archivist/service/KakaoService.java, src/main/java/com/beside/archivist/service/KakaoServiceImpl.java, src/main/resources/application.properties
카카오 소셜로그인 베이스 구축 ( #5) 리팩토링
- clientId, accesstokenuri 등 .properties 에서 값을 불러오도록 변경
- HttpURLConnection, BufferedReader 통신을 WebClient 로 변경
- obejctMapper.readValue 로 인한 연쇄적 IOException 제거를 위해 Gson 으로 변경
=> refactor: 카카오 소셜 로그인 구현 (#5)

src/main/java/com/beside/archivist/ArchivistApplication.java, src/main/java/com/beside/archivist/config/AuditConfig.java, src/main/java/com/beside/archivist/config/AuditorAwareImpl.java
등록/수정자 추적을 위한 AuditorAware 설정 추가 (#37)
-  AuditorAware 를 빈으로 등록하여 북마크 등을 등록/수정한 회원의 이메일 저장
- 인증이 필요없는 경우에는 등록/수정 회원 저장 X
- 회원 TB 에서는 등록/수정자를 저장할 필요가 없어서 분리에 대한 논의 필요.
=> feat: 등록/수정자 추적을 위한 AuditorAware 설정 추가 (#37)

src/main/java/com/beside/archivist/exception/ExceptionCode.java, src/main/java/com/beside/archivist/exception/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/users/UserAlreadyExistsException.java, src/main/java/com/beside/archivist/service/users/UserService.java, src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
유효성 검증 시 중복 회원 검증 로직 추가 (#44)
- 예외 코드 ( ExceptionCode - code ) USER_xxx 포맷 사용
- 회원 가입 시 유니크 값이어야하는 이메일이 이미 사용되고 있을 때 예외 발생
- 지속적으로 업데이트 예정. 개선 사항이 있다면 말씀 부탁드립니다.
=> feat: 중복 회원 검증 로직 추가 (#44)

src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java, src/main/java/com/beside/archivist/entity/users/User.java, src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java, src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java
회원 연관관계 매핑 추가 (#50)
- User 엔티티에 Bookmark와의 1:N 관계 설정
- BookmarkRepository 에서 외래키를 통해 조회하기위해 **findBy참조테이블_가져오고싶은필드** 로 인터페이스 재정의
- 순환 참조로 인해 응답값 변경 후 테스트 가능합니다.
=> feat: 회원 연관관계 매핑 추가 (#50)

src/main/java/com/beside/archivist/controller/users/UserController.java, src/main/java/com/beside/archivist/dto/users/KakaoLoginDto.java, src/main/java/com/beside/archivist/exception/ExceptionCode.java, src/main/java/com/beside/archivist/exception/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/users/UserNotFoundException.java, src/main/java/com/beside/archivist/service/users/KakaoService.java, src/main/java/com/beside/archivist/service/users/KakaoServiceImpl.java
소셜 로그인 시 코드 리팩토링 및 예외 처리 개선 (#52)
- KakaoLoginDto 에서 사용하지 않는 필드 제거 
- 소셜 로그인 성공 시 정의되지않은 response 값 -> KakaoLoginDto 로 변경
- 소셜 로그인 실패 시 ( 회원가입하지 않은 초기 유저 ) 예외 처리 로직 개선
=> refactor: 소셜 로그인 시 코드 리팩토링 및 예외 처리 개선 (#52)

src/main/java/com/beside/archivist/controller/users/UserController.java, src/main/java/com/beside/archivist/entity/users/Category.java
Category 값 재정의 및 조회 API 구현 (#67)
-  Category 값 재정의 - 외국어, 자기계발, 문화생활, 사진, 운동, 재테크, 취미, 여행, 드로잉, 커리어
- 카테고리에 정의된 모든 값을 조회하는 API 추가
- 확정된 사항인지 재확인 필요
- FE 전달
=> Category 값 재정의 및 조회 API 구현 (#67)

src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/images/InvalidFileExtensionException.java, src/main/java/com/beside/archivist/service/util/FileService.java
이미지 업로드 시 jpg/jpeg/png 외 확장자 예외 처리 추가 (#70)
- jpg/jpeg/png 외 확장자 예외 처리 추가
- WebIA 문서 상 아래 이미지처럼 표기되어있어서 우선 크기 제한은 추가 안했습니다!
=> feat: 이미지 업로드 시 jpg/jpeg/png 외 확장자 예외 처리 추가 (#70)

src/main/java/com/beside/archivist/controller/group/GroupController.java, src/main/java/com/beside/archivist/dto/group/GroupDto.java, src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java, src/main/java/com/beside/archivist/entity/group/Group.java, src/main/java/com/beside/archivist/entity/users/User.java, src/main/java/com/beside/archivist/mapper/GroupMapper.java, src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java, src/main/java/com/beside/archivist/repository/group/GroupRepository.java, src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java, src/main/java/com/beside/archivist/service/bookmark/BookmarkServiceImpl.java, src/main/java/com/beside/archivist/service/group/GroupService.java, src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java, src/main/java/com/beside/archivist/service/users/UserService.java, src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
회원과 그룹간 Bookmark 테이블 작업 (#71)
- 회원-그룹 N:N 관계 해소를 위한 Bookmark 테이블 추가
- 그룹은 회원을 바로 보고있지 않으므로 user 필드 모두 사용 중지 ( 주석 처리 )
- 그룹 생성 API 에서 그룹 데이터에 회원 데이터를 저장하는 대신 Bookmark 에서 그룹 및 회원 데이터 저장
- 코드 리뷰 이후 userId 제거 및 관련 API 처리 ( ex> 특정 유저의 그룹 조회하기 ) 
- 다른 사람의 그룹을 북마크하는 API 구현해야 함. ( isOwner 필드가 false )
=> feat: 회원과 그룹간 Bookmark 테이블 작업 (#71)

src/main/java/com/beside/archivist/controller/users/UserController.java, src/main/java/com/beside/archivist/dto/exception/LoginFailureDto.java, src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/users/EmailTokenMismatchException.java, src/main/java/com/beside/archivist/exception/users/UserNotFoundException.java, src/main/java/com/beside/archivist/service/users/KakaoServiceImpl.java
회원 가입 API 토큰 인증 적용 (#80)
- 로그인 실패 시 응답 값 변경 : 로그인 실패 시에 token 값 추가로 인해 DTO 재정의 ( LoginFailureDto 추가 )
- 회원가입 API 토큰 인증 적용 : JWTfiler 를 먼저 거쳐서 토큰 인증을 하게 되면 Response 값의 email 값을 재사용할 수 없기 때문에 Controller 단에서 받아서 처리
- token 에서 추출한 email 과 응답받은 email 정보가 다를 때 예외 처리 추가 구현 ( EmailTokenMismatchException )
=> feat: 회원 가입 API 토큰 인증 적용 (#80)

src/main/resources/application-prod.properties
NCP 스토리지로 이미지 저장소 변경
- 블록 스토리지 xen(하이퍼바이저), ssd(스토리지 종류)로 생성
- /mnt/xvdb1 에 /dev/xvdb1 와 마운트
- 이미지 저장 경로 /mnt/xvdb1로 변경
- 블록 스토리지 용량
- 운영 테스트 필요
=> feature : NCP 스토리지로 이미지 저장소 변경  (#72)

src/main/java/com/beside/archivist/controller/users/UserController.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
로그인 API 응답 시 헤더에 Token 추가 (#82)
- 로그인 성공 시 쿠키에 토큰 정보 추가
- 로그인 실패 예외 발생 시에도 쿠키에 토큰 정보 추가
- body 에서 header로 변경이 된 게 아니라 둘 다 응답 -> FE 요청
- header 에서 토큰 탈취에 대한 보안 이슈 고려
=> feat: 로그인 API 응답 시 헤더에 Token 추가 (#82)

src/main/java/com/beside/archivist/config/SecurityConfig.java, src/main/java/com/beside/archivist/controller/users/UserController.java, src/main/java/com/beside/archivist/service/users/UserService.java, src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
닉네임 조회 API 구현 (#86)
- 회원 DB에 저장되어있는 모든 닉네임을 조회하는 API 추가
- 해당 API 토큰 인증 해제
- FE 전달
=> feat: 닉네임 조회 API 구현 (#86)

src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/users/SignUpRequiredException.java, src/main/java/com/beside/archivist/exception/users/UserNotFoundException.java, src/main/java/com/beside/archivist/service/users/KakaoServiceImpl.java, src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
UserNotFound 분리 및 재정의 (#88)
- 회원가입을 해야하는 초기 유저가 로그인 하였을 때와 그 외에 회원 데이터가 DB에 없을 때 예외를 분리
- SignUpRequiredException 정의
- UserNotFound 적용
=> refactor: UserNotFound 분리 및 재정의 (#88)

src/main/java/com/beside/archivist/dto/users/UserDto.java, src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
API 요청 시 필수 값에 대한 검증 및 예외 처리 (#89)
- API 요청 시 userDto, linkDto 등 필수 값 누락에 대한 예외 처리 ( ErrorCode: VALID_001 )
- UserDto 필드 검증을 위한 @NotBlank 및 @NotEmpty 어노테이션 추가
- 예외 처리는 전역적으로 적용되나 null 값에 대한 예외처리는 다른 DTO 에도 적용이 되어야 할 것 같습니다!
=> feat: API 요청 시 필수 값에 대한 검증 및 예외 처리 (#89)

src/main/java/com/beside/archivist/controller/group/GroupController.java, src/main/java/com/beside/archivist/repository/usergroup/UserGroupRepository.java, src/main/java/com/beside/archivist/service/group/GroupService.java, src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java, src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java, src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
회원이 생성한 그룹 조회 API 변경 (#100)
- 회원-그룹 간 UserGroup 테이블을 중간 테이블로 재설계했기때문에 회원의 그룹 조회 API 변경
- 회원 본인이 생성한 그룹들 모두 조회 ( 북마크 X -> isOwner 가 true ) 
- 그룹 북마크하는 API 생성 후 북마크한 그룹들 조회하는 API 따로 구현 예정
=> refactor: 회원이 생성한 그룹 조회 API 변경 (#100)

src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
카카오 인가 코드 만료에 대한 예외 처리 추가 (#103)
- 카카오 인가 코드가 만료된 경우 500 으로 응답되어 예외 처리 추가 ( USER_005 )
- API 접근 제어 설정( 1/13 업데이트 예정 )하기 전까지는 401 로 반환됩니다.
=> feat: 카카오 인가 코드 만료에 대한 예외 처리 추가 (#103)

src/main/java/com/beside/archivist/config/SecurityConfig.java, src/main/java/com/beside/archivist/controller/group/GroupController.java, src/main/java/com/beside/archivist/controller/link/LinkController.java
API 접근 제어 설정 (#104)
- 기존에 토큰 인증 API 에 대한 정리가 안되어있어 SecurityConfig 에 재정의
- anyRequest().authenricated() -> anyRequest().permitAll() 로 변경 ( 이거 때문에 500으로 안떨어지고 401 로 떨어짐 )
- LinkController 및 GroupController 에서 id 로 표기되어있는 경로 변수명 변경
- 현재 구현되지 않은 API 에 대한 토큰 인증여부 정의 필요
=> fix: API 접근 제어 설정 (#104)

src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/group/GroupNotFoundException.java, src/main/java/com/beside/archivist/exception/link/LinkNotFoundException.java, src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java, src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java, src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java, src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
삭제한 링크 및 그룹 데이터 없을 때 예외 처리
- LinkNotFoundException 정의
- GroupNotFoundException 정의
- 토큰인증 시 유저정보가 없을 경우 예외처리 추가(?)
- linkGroup 중복 등록 예외처리 추가
=> feat: 링크 및 그룹 데이터 없을 때 예외 처리 (#102) 

src/main/resources/application-prod.properties
Hibernate DDL 자동 설정 update로 변경 (#111)
- 운영 환경에서 Hibernate DDL 설정을 create -> update 로 변경
- 잦은 push 로 인해 기존 데이터 손실 방지를 위해 변경하나 새로운 필드/테이블 추가 시에 null 값 체크 필요.
=> chore: Hibernate DDL 자동 설정 update로 변경 (#111)

src/main/java/com/beside/archivist/controller/group/LinkGroupController.java, src/main/java/com/beside/archivist/entity/group/GroupImg.java, src/main/java/com/beside/archivist/entity/link/LinkImg.java, src/main/java/com/beside/archivist/repository/group/GroupRepository.java, src/main/java/com/beside/archivist/repository/group/LinkGroupRepository.java, src/main/java/com/beside/archivist/service/group/GroupImgService.java, src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java, src/main/java/com/beside/archivist/service/group/GroupService.java, src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java, src/main/java/com/beside/archivist/service/group/LinkGroupService.java, src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java, src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
그룹 썸네일 예외 처리 (#78)
재사용성을 고려하여 *Img 클래스에 정적 팩터리 메서드 추가 (#113)
- 재사용성을 고려하여 *ImgService 에 정의된 DefaultImage() 내 로직을 정적 팩터리 메서드로 재정의 ( GroupImg, LinkImg )
- 그룹 생성 ( 처음에 이미지 업로드 안했을 때 링크 저장 안되어있으니까 링크 디폴트 이미지 저장 - 기존과 동일 )
- 그룹에 링크를 추가했을 때
1. 링크가 디폴트 이미지일 때 -> 디폴트 이미지 유지
2. 링크가 디폴트 이미지가 아닐 때 -> 링크 이미지로 업데이트
- 그룹 내 링크를 삭제했을 때
1. 링크 이미지와 그룹 이미지가 같을 때 -> 기존 이미지가 아닌 새로운 링크 이미지로 업데이트 ( 위의 로직을 따라갑니다. ) 
2. 링크 이미지와 그룹 이미지가 다를 때 -> 기존 이미지 유지
- 현재 #114 의 문제가 발생하여 링크 삭제했을 때의 로직을 추가하지 못했습니다! 하기 이슈 처리해주시면 진행할게요.
- 코드 가독성 및 description 이 괜찮은가 에 대한 코멘트도 부탁드려요!
=> feat: 그룹 썸네일 예외 처리 (#78)

src/main/java/com/beside/archivist/controller/users/UserController.java, src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/users/MissingAuthenticationException.java, src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java, src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
요청 헤더에 인증 토큰이 없는 경우 예외 처리 (#109)
- Service / Controller 단에서 토큰을 통해 유저 정보를 처리하는 경우에 Authentication 이 null 값으로 들어와 예외 처리 ( USER_006 )
- filter 단에서 Map 으로 응답하는 인증 관련 응답은 이슈 따로 파서 예외 코드 정의하고 리팩토링 하겠습니다!
=> feat: 요청 헤더에 인증 토큰이 없는 경우 예외 처리 (#109)

src/main/java/com/beside/archivist/dto/group/GroupDto.java, src/main/java/com/beside/archivist/entity/BaseEntity.java, src/main/java/com/beside/archivist/entity/group/Group.java, src/main/java/com/beside/archivist/entity/link/Link.java, src/main/java/com/beside/archivist/entity/usergroup/UserGroup.java, src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
Entity 내 모든 boolean 필드 타입 변경 (#126)
- Group 내 isGroupPublic 타입 변경 ( Default "Y" )
- BaseEntity 내 isDeleted 타입 변경 ( Default "N" )
- @ColumnDefault 값 적용을 위해 @DynamoInsert 어노테이션 추가
- 삭제 시 값을 업데이트하기 위해 @DynamoUpdate 어노테이션 추가
- User Entity 는 BaseEntity 를 상속받고 있지 않습니다. Soft Delete 적용 범위 확인 부탁드립니다!
=> refactor: Entity 내 모든 boolean 필드 타입 변경 (#126)

src/main/java/com/beside/archivist/config/AuditorAwareImpl.java, src/main/java/com/beside/archivist/config/SecurityConfig.java, src/main/java/com/beside/archivist/config/filters/JwtRequestFilter.java, src/main/java/com/beside/archivist/entity/link/Link.java
관리자 계정 생성을 위한 권한 분리
- 특정 email에 admin 권한 부여, 나머지는 user
- 추후에 관리자로 사용될 email로 수정
- 하드코딩으로 되어 있어 db에서 user 권한을 설정하는 방법도 고려해봐야함
=> 관리자 계정 생성을 위한 권한 분리

src/main/java/com/beside/archivist/config/AuthenticationEntryPointImpl.java, src/main/java/com/beside/archivist/config/filters/JwtExceptionFilter.java, src/main/java/com/beside/archivist/config/filters/JwtRequestFilter.java, src/main/java/com/beside/archivist/exception/common/ExceptionCode.java, src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java, src/main/java/com/beside/archivist/exception/users/InvalidTokenException.java, src/main/java/com/beside/archivist/exception/users/TokenExpiredException.java
토큰 관련 예외 처리 재정의 (#134)
- Map<Integer,String> 타입으로 정의된 응답 메시지를 예외 코드로 재정의 하여 재정의
- 토큰 만료 시 TokenExpiredException 발생 ( USER_007)
- 토큰이 잘못되었거나 그에 대한 회원 정보가 존재하지 않을 때 InvalidTokenException 발생( USER_008 )
- Filter 단에서 발생하는 예외는 Dispatcher Servlet이 처리하기 전에 발생하기 때문에 GlobalController 에서 처리가 불가하여 USER_007 은 추가하지 않았습니다. USER_008 을 추가한 이유는 회원 정보 저장 API 에서는 토큰 검증을 Controller 에서 하기 때문입니다.
=> refactor: 토큰 관련 예외 처리 재정의 (#134)

src/main/java/com/beside/archivist/config/SecurityConfig.java
CORS 화이트리스트에 운영 및 테스트 도메인 추가 (#144)
- 운영 도메인 추가 ( http://arcave-official.com/ )
- 테스트 도메인 추가 ( http://test.arcave-official.com, http://stage.arcave-official.com )
=> chore: CORS 화이트리스트에 운영 및 테스트 도메인 추가 (#144)

src/main/java/com/beside/archivist/controller/link/LinkController.java, src/main/java/com/beside/archivist/service/group/LinkGroupService.java, src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
링크 초기 저장 시 그룹 이미지 업데이트 안되는 버그 수정 (#154)
- groupId 배열을 매개변수로 하는 changeGroupImgArray 인터페이스 추가
- 링크 저장 시 그룹 이미지 업데이트 안되는 버그 수정
- 링크 삭제했을 때 그룹 이미지 업데이트 코드 추가 예정
=> 링크 초기 저장 시 그룹 이미지 업데이트 안되는 버그 수정 (#154)

src/main/java/com/beside/archivist/entity/group/Group.java, src/main/java/com/beside/archivist/entity/group/GroupImg.java, src/main/java/com/beside/archivist/service/group/GroupImgService.java, src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java, src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
Group-GroupImg 관계 재설정 및 코드 변경 (#167)
- Group-GroupImg 관계를 자식-부모 → 부모-자식 으로 변경
- 관계 재설정에 따라 서비스 코드 변경
- 메서드명 오타 수정 ( changeLinkImg → changeGroupImg )
- GroupService 내 Description 추가
- Link-LinkImg 관계 설정 확인
=> Group-GroupImg 관계 재설정 및 코드 변경

src/main/java/com/beside/archivist/entity/group/Group.java
isGroupPublic 필드가 null 값일 때 'Y' 값 설정 (#176)
- isGroupPublic 의 @DefaultColumn 설정 제거
- Group Builder 내에 isGroupPublic 이 null 값일 때 'Y' 값 저장하도록 설정
=> isGroupPublic 필드가 null 값일 때 'Y' 값 설정 (#176)

src/main/java/com/beside/archivist/dto/group/GroupDto.java
groupName Null 값인 경우 String.trim() 사용하지 않도록 변경 (#178)
- groupName null 인 경우 groupName 그대로 둬서 NotBlank 타도록 변경
=> groupName Null 값인 경우 String.trim() 사용하지않도록 변경 (#178)

src/main/java/com/beside/archivist/config/SecurityConfig.java
FE 오피셜 도메인 CORS 화이트리스트 추가 (#235)
- FE 오피셜 도메인 CORS 화이트리스트 추가
- 배포 확인 요망
=> FE 오피셜 도메인 CORS 화이트리스트 추가
