- src/main/java/com/beside/archivist/controller/users/UserController.java
- src/main/java/com/beside/archivist/service/users/UserService.java
- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
회원 정보 조회 기능 추가 (#11)
- 회원 정보 조회 기능 구현
- CRUD 에서 조회 기능이 빠져있어서 추가 구현했습니다.
> feat: 회원 정보 조회 기능 추가 (#11)

- build.gradle
- src/main/java/com/beside/archivist/config/SecurityConfig.java
- src/main/resources/application-prod.properties
배포 환경(운영) 설정 (#25)
- 운영에서 사용하기 위한 profiles 추가하여 properties 파일 분리
- 운영 환경에서 애플리케이션을 정상적으로 종료하기위한 endpoint 생성
- actuator 의존성 추가
- 보안 이슈로 인해 shutdown endpoint 리팩토링 필요
- properties 파일 공통 부분이 중복되어있어 이후 common 으로 분리하여 중복 코드 제거 필요
> chore: 배포 환경(운영) 설정 (#25)

- build.gradle
- src/main/java/com/beside/archivist/config/SecurityConfig.java
- src/main/java/com/beside/archivist/config/SwaggerConfig.java
- src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
- src/main/java/com/beside/archivist/controller/users/UserController.java
- src/main/resources/application-prod.properties
Swagger 에 JWT 설정 추가 (#26)
- Swagger 에 JWT 인증이 필요한 엔드포인트에서 인증 가능
- SwaggerConfig 를 통해 JWT 설정 및 인증이 필요한 모든 엔드포인트에 어노테이션 추가
- 모든 어노테이션이 중복으로 들어가는데 줄일 수 있는 방법이 있는 지 고려 필요.
> chore: Swagger 에 JWT 설정 추가 (#26)

- src/main/java/com/beside/archivist/ArchivistApplication.java
- src/main/java/com/beside/archivist/entity/BaseEntity.java
- src/main/java/com/beside/archivist/entity/bookmark/Bookmark.java
- src/main/java/com/beside/archivist/entity/users/User.java
BaseEntity 생성 (#20)
- 생성자, 생성일시, 수정자, 수정일시를 필드로 갖는 BaseEntity 생성 및 상속
- Instant 타입 참고
> feat : BaseEntity 생성 (#20)

- src/main/java/com/beside/archivist/controller/users/UserController.java
- src/main/java/com/beside/archivist/service/users/UserService.java
- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
회원 조회 API 변경 (#42)
-  userId 가 아닌 토큰을 통해 유저 정보 응답하도록 변경
- /user/{userId} -> /user 로 API 변경
> refactor: 회원 조회 API 변경 (#42)

- src/main/java/com/beside/archivist/exception/ExceptionCode.java
- src/main/java/com/beside/archivist/exception/ExceptionResponse.java
- src/main/java/com/beside/archivist/exception/GlobalExceptionController.java
공통 예외 처리 베이스 구축 (#22)
-  전역 처리를 위한 GlobalExceptionController 구현
- 유지보수를 용이하게 하기위해 ExceptionCode Enum 타입으로 정의
- 공통 응답 값을 정의한 ErrorResponse 생성
- Exception Code 규칙에 대한 논의 필요.
> feat: 공통 예외 처리 베이스 구축 (#22)

- src/main/java/com/beside/archivist/service/bookmark/BookmarkImgServiceImpl.java
- src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
이미지 경로 수정
**주요 변경 사항**
- properties 의 user이미지와 bookmark 이미지 경로 변경
**고려 사항**
- 디폴트 이미지의 경로 논의
> refactor : 이미지 경로 수정 (#48)

- src/main/java/com/beside/archivist/controller/users/UserController.java
- src/main/java/com/beside/archivist/dto/users/UserDto.java
- src/main/java/com/beside/archivist/exception/GlobalExceptionController.java
- src/main/java/com/beside/archivist/exception/ValidExceptionDto.java
회원 유효성 검증 및 예외 처리 (#44)
- 회원 email, nickname 유효성 검증
- Validation 공통 예외 처리 추가
> feat: 회원 유효성 검증 및 예외 처리 (#44)

- src/main/java/com/beside/archivist/dto/exception/ExceptionDto.java
- src/main/java/com/beside/archivist/dto/exception/ValidExceptionDto.java
- src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
- src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
- src/main/java/com/beside/archivist/exception/users/UserAlreadyExistsException.java
- src/main/java/com/beside/archivist/exception/users/UserNotFoundException.java
- src/main/java/com/beside/archivist/service/users/KakaoServiceImpl.java
- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
객체명 변경 및 패키지 이동 (#63)
- ExceptionResponse -> ExceptionDto 로 변경
- exception 패키지의 *Dto 객체 모두 dto 하위 exception 패키지로 이동
- GlobalExceptionController 와 ExceptionCode 를 exception 하위 common 패키지로 이동
> refactor: 객체명 변경 및 패키지 이동 (#63)

- src/main/java/com/beside/archivist/controller/users/UserController.java
회원 수정 API 개선 (#65)
- 회원 수정 API 요청값 UserDto 에 @Valid 추가
- 회원 수정 API @PostMapping 에서 @PatchMapping 으로 변경
> fix: 회원 수정 API 개선 (#65)

- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/dto/link/LinkDto.java
- src/main/java/com/beside/archivist/entity/link/Link.java
- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
title, description 의 유효성 검증
-  IA 문서을 참조하여 유효성 조건 확인
-  이모지 사용을 위한 문자 인코딩방식 변경
-  링크 등록,수정,삭제시 null 리턴값 변경
> feature : 북마크 유효성 검증 - title, description (#57)

- src/main/java/com/beside/archivist/controller/group/GroupController.java
- src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
- src/main/java/com/beside/archivist/dto/group/GroupDto.java
- src/main/java/com/beside/archivist/dto/group/LinkGroupDto.java
- src/main/java/com/beside/archivist/entity/group/Group.java
- src/main/java/com/beside/archivist/entity/group/GroupImg.java
- src/main/java/com/beside/archivist/entity/group/LinkGroup.java
- src/main/java/com/beside/archivist/repository/group/GroupImgRepository.java
- src/main/java/com/beside/archivist/repository/group/GroupRepository.java
- src/main/java/com/beside/archivist/repository/group/LinkGroupRepository.java
- src/main/java/com/beside/archivist/service/group/GroupImgService.java
- src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java
- src/main/java/com/beside/archivist/service/group/GroupService.java
- src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
- src/main/java/com/beside/archivist/service/group/LinkGroupService.java
- src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
그룹 crud 추가 및 연관관계 매핑
- 그룹 crud 생성
- 그룹 링크 crud 생성
- 특정 그룹 링크 조회
> feat: 그룹 crud 추가 및 연관관계 매핑 (#73)

- build.gradle
- src/main/java/com/beside/archivist/mapper/GroupMapper.java
- src/main/java/com/beside/archivist/mapper/LinkGroupMapper.java
- src/main/java/com/beside/archivist/mapper/LinkMapper.java
- src/main/java/com/beside/archivist/mapper/UserMapper.java
- src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
- src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
Mapstruct 적용하여 중복 코드 제거 (#47)
- 각 Entity 의 Mapper 클래스 생성
- toDto <-> Entity 메서드를 통해 중복 코드 제거
> refactor: Mapstruct 적용하여 중복 코드 제거 (#47)

- src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
- src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
이미지 업로드 시 10MB 이상 파일에 대한 예외 처리 추가 (#70)
- 이미지 크기 10MB 로 제한
- ExceptionCode 에 IMAGE_002 코드 추가
- 10MB 초과 시 FileSizeLimitExceededException 발생하여 IMAGE_002 코드로 처리
- FE 의견에 따라 변경될 수 있음.
> feat: 이미지 업로드 시 10MB 이상 파일에 대한 예외 처리 추가 (#70)

- src/main/java/com/beside/archivist/config/SecurityConfig.java
카테고리 조회 API 인증 해제 (#67)
- /categories 로 들어오는 요청 모두 허용 ( 인증 해제 )
> chore: 카테고리 조회 API 인증 해제 (#67)

- src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
- src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
- src/main/java/com/beside/archivist/exception/users/InvalidCategoryNameException.java
- src/main/java/com/beside/archivist/service/users/UserService.java
- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
정의되지 않은 카테고리 값 예외 처리 (#87)
- ENUM 에 정의되어있지 않은 카테고리가 null 값으로 저장되어 예외 처리 ( ErrorCode : CATEGORY_001 )
> feat: 정의되지 않은 카테고리 값 예외 처리 (#87)

- src/main/java/com/beside/archivist/controller/group/GroupController.java
- src/main/java/com/beside/archivist/entity/group/Group.java
- src/main/java/com/beside/archivist/entity/usergroup/UserGroup.java
- src/main/java/com/beside/archivist/entity/users/User.java
- src/main/java/com/beside/archivist/repository/bookmark/BookmarkRepository.java
- src/main/java/com/beside/archivist/repository/usergroup/UserGroupRepository.java
- src/main/java/com/beside/archivist/service/bookmark/BookmarkService.java
- src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
- src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
Bookmark → UserGroup 으로 테이블명 변경 (#96)
- Bookmark Entity/Service/Controller 모두 UserGroup* 으로 변경
- Bookmark 의미와 혼동되어 모두 UserGroup 으로 변경하였는데, 북마크 API는 따로 구현되어야 함.
> refactor: Bookmark → UserGroup 으로 테이블명 변경 (#96)

- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
- 저장 - 링크 png,jpg,jpeg 외 확장자가 들어왔을 때 디폴트 이미지로 처리
- 수정 - 확장자 제한 유지
> feature : 링크 썸네일 예외 처리 (#90)

- src/main/java/com/beside/archivist/controller/group/GroupController.java
- src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/controller/users/UserController.java
모든 API 에 OK 200 응답으로 되어있는데 생성 시에는 Created 201 등 맞는 응답으로 재정의
- 모든 API 에 OK 200 응답으로 되어있는데 생성 시에는 Created 201 등 맞는 응답으로 재정의
> refactor : API 응답 시 HttpStatus 재정의 (#92)

- src/main/java/com/beside/archivist/config/SecurityConfig.java
- src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
- src/main/java/com/beside/archivist/controller/group/GroupController.java
- src/main/java/com/beside/archivist/repository/usergroup/UserGroupRepository.java
- src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
- src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
그룹 북마크 기능 추가 및 개선 (#116)
- bookmark 관련 API 모두 토큰 인증 요구
- 그룹 북마크 기능 및 API 
- 내가 북마크한 그룹 조회 기능 및 API
- 북마크 제거 기능 및 API
- 지난번에 코멘트 달아주셨던 거 issues 따서 QueryDsl 적용해보겠습니다~
> feat: 그룹 북마크 기능 추가 및 개선 (#116)

- src/main/java/com/beside/archivist/entity/link/Link.java
> fix : Link 와 LinkGroup 간 양방향 설정 (#114)

- src/main/java/com/beside/archivist/entity/BaseEntity.java
- src/main/java/com/beside/archivist/entity/BaseTimeEntity.java
- src/main/java/com/beside/archivist/entity/group/Group.java
- src/main/java/com/beside/archivist/entity/group/LinkGroup.java
- src/main/java/com/beside/archivist/entity/link/Link.java
- src/main/java/com/beside/archivist/entity/usergroup/UserGroup.java
- BaseEntity 에 is_Delete 필드 추가
- BaseTImeEntity 에 deleted_at필드 추가
- linkGroup에 BaseEntity 제거
- delete 요청 변환, 조회 is_delete 조건 추가
> feature : Delete Soft (#91)

- src/main/java/com/beside/archivist/controller/bookmark/BookmarkController.java
- src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
- src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
- src/main/java/com/beside/archivist/exception/group/GroupAlreadyExistsException.java
- src/main/java/com/beside/archivist/exception/link/GroupInBookmarkNotFoundException.java
- src/main/java/com/beside/archivist/service/usergroup/UserGroupService.java
- src/main/java/com/beside/archivist/service/usergroup/UserGroupServiceImpl.java
그룹 북마크 관련 예외 처리 추가(#125)
- 북마크한 그룹 삭제 시에 북마크 그룹 내 그룹 정보가 없을 때 예외 처리 ( GROUP_002 )
- 그룹 북마크 시에 내 그룹은 안되도록 중복 체크 ( GROUP_003 )
- 그룹 북마크 시에 이미 북마크 했을 경우 중복 체크 ( GROUP_003 )
> feat: 그룹 북마크 관련 예외 처리 추가(#125)

- src/main/java/com/beside/archivist/entity/link/Link.java
- src/main/java/com/beside/archivist/service/group/GroupImgService.java
- src/main/java/com/beside/archivist/service/group/GroupImgServiceImpl.java
- src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
- src/main/java/com/beside/archivist/service/link/LinkImgService.java
- src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
- src/main/java/com/beside/archivist/service/users/UserImgService.java
- src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
- *service 에 정의된 update* 인터페이스명 change로 재정의
> *ImgService 에 정의된 update* 인터페이스명 재정의

- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/dto/link/LinkInfoDto.java
- src/main/java/com/beside/archivist/repository/group/LinkGroupRepository.java
- src/main/java/com/beside/archivist/service/group/LinkGroupService.java
- src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
- src/main/java/com/beside/archivist/service/link/LinkService.java
- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
- 링크 등록 시 groupId를 배열로 받아서 groupLink 같이 등록
- 링크 수정 시 groupLink 를 삭제하고 groupId를 배열로 받아서 재등록
> refactor : 그룹 내 링크 추가/수정 기능을 링크 API 에 추가 (#123)

- src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
- src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
- src/main/java/com/beside/archivist/exception/group/GroupInBookmarkNotFoundException.java
- src/main/java/com/beside/archivist/exception/link/LinkInGroupNotFoundException.java
- src/main/java/com/beside/archivist/service/group/LinkGroupService.java
- src/main/java/com/beside/archivist/service/group/LinkGroupServiceImpl.java
그룹 내 링크가 존재하지 않을 때 예외 처리 추가 (#152)
- linkGroupId 가 존재하지 않을 때 예외 처리 추가 ( LINK_002 )
> feat: 그룹 내 링크가 존재하지 않을 때 예외 처리 추가 (#152)

- src/main/java/com/beside/archivist/controller/users/UserController.java
- src/main/java/com/beside/archivist/entity/users/User.java
- src/main/java/com/beside/archivist/entity/users/UserImg.java
- src/main/java/com/beside/archivist/service/users/UserImgService.java
- src/main/java/com/beside/archivist/service/users/UserImgServiceImpl.java
- src/main/java/com/beside/archivist/service/users/UserService.java
- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
User-UserImg 관계 재설정 및 코드 변경 (#155)
- User-UserImg 관계를 자식-부모 → 부모-자식 으로 변경
- 관계 재설정에 따라 서비스 코드 변경
- Link-LinkImg 도 수정 필요
> User-UserImg 관계 재설정 및 코드 변경

- build.gradle
- src/main/resources/application.yml
p6spy 의존성 추가 (#165)
- p6spy 의존성 추가
- application.yml 내 로깅 설정 추가
> chore: p6spy 의존성 추가 (#165)

- src/main/java/com/beside/archivist/entity/BaseEntity.java
- src/main/java/com/beside/archivist/entity/group/Group.java
- src/main/java/com/beside/archivist/entity/link/Link.java
- src/main/java/com/beside/archivist/entity/users/User.java
- src/test/java/com/beside/archivist/entity/BaseEntityTest.java
isDeleted 필드 @DefaultColumn → @PrePersist 로 디폴트 값 재설정 (#168)
- isDeleted 필드 @DefaultColumn → @PrePersist 로 디폴트 값 재설정
- Group, Link, User 내 @DynamicInsert 및 @DynamicUpdate 제거
- 우려 사항 있으시면 말씀 부탁드립니다.
> isDeleted 필드 @DefaultColumn → @PrePersist 로 디폴트 값 재설정 (#168)

- README.md
ERD 추가 및 README 업데이트 (#175)
- Readme 파일 내 ERD 추가
- 패키지 구조에 mapper 업데이트
> ERD 추가 및 README 업데이트 (#175)

- src/test/java/com/beside/archivist/controller/group/GroupControllerTest.java
- src/test/java/com/beside/archivist/service/group/GroupServiceTest.java
Group 관련 Test Code 작성 (#118)
- Service Layer
- Controller Layer
- Exception
- 링크 이미지 업데이트에 따른 GroupImg 변경 관련 테스트는 링크 이미지 관계 재설정 이후 진행하겠습니다!
> Group 관련 Test Code 작성 (#118)

- src/main/java/com/beside/archivist/controller/group/GroupController.java
- src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/controller/users/UserController.java
삭제 요청에 대한 응답 status 200 → 204 변경 (#181)
- 모든 Controller 내 DeleteMapping 응답 Status NO_CONTENT 로 변경
> 삭제 요청에 대한 응답 status 200 → 204 변경 (#181)

- src/main/java/com/beside/archivist/controller/group/GroupController.java
- src/main/java/com/beside/archivist/controller/group/LinkGroupController.java
- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/controller/users/UserController.java
- src/main/java/com/beside/archivist/entity/link/Link.java
- src/main/java/com/beside/archivist/entity/link/LinkImg.java
- src/main/java/com/beside/archivist/service/link/LinkImgService.java
- src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
- src/test/java/com/beside/archivist/controller/group/GroupControllerTest.java
- src/test/java/com/beside/archivist/service/group/GroupServiceTest.java
group-groupImg link-linkImg 관계 수정
- group 부모- groupImg 자식 관계로 변경
- link 부모 - linkImg 자식 관계로 변경
- 자식의 고아객체 삭제
> fix : group-groupImg link-linkImg 관계 수정 (#174)

- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
링크 저장 내 객체 저장 및 이미지 조건 로직 변경 (#188)
- 이미지 파일이 있는 경우 insert 하게끔 조건 로직 수정 
- LinkImg 에 저장된 Link 객체를 저장하도록 로직 수정
- 체크해주시면 #186 머지 이후 머지하겠습니다.
> 링크 저장 내 객체 저장 및 이미지 조건 로직 변경 (#188)

- src/main/java/com/beside/archivist/exception/common/ExceptionCode.java
- src/main/java/com/beside/archivist/exception/common/GlobalExceptionController.java
필수 값 누락 시 클라이언트에 누락된 필드명 반환하도록 메시지 수정 (#196)
- ExceptionCode 내 parameter 를 포함할 수 있는 getMessageWithParameter 메서드 생성
- 필수 값 누락 시 클라이언트에 누락된 필드명 반환하도록 응답 메시지 수정
- 위 변경 사항은 RequestPart 애노테이션으로 받는 값에 대한 검증입니다. 
- develop 에 redis 적용한 거 pull 받아와서 정상 동작되는 지 테스트 부탁드립니다. 또한, redis 반영으로 인한 이점에 대해 말씀 부탁드려요
> 필수 값 누락 시 클라이언트에 누락된 필드명 반환하도록 메시지 수정 (#196)

- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/service/link/LinkImgServiceImpl.java
링크 이미지 URL Null 값 저장 이슈 (#195)
- LinkImg 디폴트 이미지 혹은 파일 저장 시 Link 내 저장 로직 추가 ( 양방향 저장 )
- LinkController 내 오탈자 수정
- #199 #200  확인 부탁드립니다.
> 링크 이미지 URL Null 값 저장 이슈 (#195)

- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/service/link/LinkService.java
- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
링크 저장 시 groudId 필수값으로 변경 (#194)
- LinkController 내 groupId 리스트 필수 값으로 변경
- LinkServiceImpl 내 Override 애노테이션 빠진 거 추가
- 가독성 높이기 위해 파라미터명 변경
- 버그 fix 관련해서 플로우 어떻게 탈건지 정리가 필요할 것 같습니다!
> 링크 저장 시 groudId 필수값으로 변경 (#194)

- src/main/java/com/beside/archivist/config/filters/JwtRequestFilter.java
- src/main/java/com/beside/archivist/controller/group/GroupController.java
- src/main/java/com/beside/archivist/controller/home/HomeController.java
- src/main/java/com/beside/archivist/controller/link/LinkController.java
- src/main/java/com/beside/archivist/controller/users/UserController.java
- src/main/java/com/beside/archivist/dto/home/HomeFeedDto.java
- src/main/java/com/beside/archivist/dto/home/HomeFeedInfoDto.java
- src/main/java/com/beside/archivist/entity/home/HomeFeed.java
- src/main/java/com/beside/archivist/mapper/GroupMapper.java
- src/main/java/com/beside/archivist/mapper/LinkMapper.java
- src/main/java/com/beside/archivist/repository/home/HomeFeedRepository.java
- src/main/java/com/beside/archivist/service/group/GroupService.java
- src/main/java/com/beside/archivist/service/group/GroupServiceImpl.java
- src/main/java/com/beside/archivist/service/home/HomeFeedService.java
- src/main/java/com/beside/archivist/service/home/HomeFeedServiceImpl.java
- src/main/java/com/beside/archivist/service/link/LinkService.java
- src/main/java/com/beside/archivist/service/link/LinkServiceImpl.java
홈 피드 API 생성 (#203)
- 불필요한 관리자용 엔드포인트 및 설정 제거 ( #10 , #130 제거 )
- 홈 피드에 노출될 그룹 및 링크 설정을 위한 엔드포인트 생성
> 홈 피드 API 생성 (#203)

- development/run_local_db.sh
로컬에서 서버를 띄우고 실행하려고 간단하게 docker 실행 script를 작성했습니다.
윈도우 환경이신 분도 있는 것 같은데, 제가 맥유저라 맥에서만 돌려보았네요..
잘부탁드립ㄴ다
local에서 서버를 띄우기 위한 의존성(redis, mysql) docker로 띄우기
* mac에서 테스트 했습니다.
> 안녕하세요. 문안인사 올립니다.

- src/main/java/com/beside/archivist/config/SecurityConfig.java
- src/main/java/com/beside/archivist/config/WebMvcConfig.java
- (https://archivist-frontend-pgonee.vercel.app/) 테스트 도메인 cors 설정
> feature: 프론트 테스트 도메인 cors 설정 (#235)

- src/main/java/com/beside/archivist/service/users/UserServiceImpl.java
* 마이프로필 API 연동 중 발견한 버그입니다.
* 유저 정보 업데이트 이후 redis 캐시가 남아있어 업데이트 이전의 데이터가 계속 보여지는 문제를 해결하였습니다.
> fix: 마이프로필 유저 저장 이후 redis 캐시 갱신
